- src/api/api.ts
- src/hooks/cache/useWatchlist.ts
Changed watcher api url to dev to prod.
> Remove watcher when removing address from watchlist

- src/api/watcher-service.ts
- src/components/templates/BottomSheetNotificationSettings/index.tsx
- src/constants/config.ts
- src/screens/Settings/index.tsx
Reverts ambrosus/airdao-mobile#81
> Revert "Stage"

- src/components/modular/Toast/Toast.styles.ts
> AIRMOB-162

- src/components/svg/icons/Logo.tsx
- src/components/templates/PortfolioPerformance/index.tsx
- src/components/templates/PortfolioPerformance/styles.ts
> AIRMOB-202

- src/components/templates/BottomSheetNotificationSettings/index.tsx
- src/screens/Notifications/index.tsx
- src/screens/Settings/components/SettingsBlock/index.tsx
- src/screens/Settings/components/SettingsBlock/modals/BottomSheetBaseCurrency/index.tsx
- src/screens/Settings/components/SettingsBlock/modals/BottomSheetSelectLanguage/index.tsx
https://github.com/ambrosus/airdao-mobile/assets/128598571/c8c77569-d184-4ff2-942a-ec31e788b4d8
> AIRMOB-217

- src/components/templates/BottomSheetNotificationSettings/index.tsx
- src/screens/Notifications/index.tsx
- src/screens/Settings/components/SettingsBlock/index.tsx
- src/screens/Settings/components/SettingsBlock/modals/BottomSheetBaseCurrency/index.tsx
- src/screens/Settings/components/SettingsBlock/modals/BottomSheetSelectLanguage/index.tsx
Reverts ambrosus/airdao-mobile#175
> Revert "AIRMOB-217"

- app.json
- src/screens/Settings/Settings.tsx
- src/utils/isPlatform.ts
add new build version and settings
> new build params

- app.json
- src/components/modular/Toast/Toast.wrapper.tsx
[3106] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3106
removed red line on top
> [3106] remove red line

- src/navigation/stacks/Tabs/HomeStack.tsx
2405  https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-2405
disabled goBack swipe on transaction status screen
> [2405] disabled goBack swipe

- src/constants/fonts.ts
- src/screens/Portfolio/components/PortfolioScreenTabs/components/PortfolioScreenTabItem/index.tsx
- src/screens/Portfolio/components/PortfolioScreenTabs/components/PortfolioScreenTabItem/styles.ts
- src/screens/Portfolio/components/PortfolioScreenTabs/index.tsx
- src/screens/Portfolio/components/PortfolioScreenTabs/styles.ts
3133 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3133
fix style differs on Watchlist-page
> [3133] Watchlist-page differs from Figma

- src/hooks/usePasscodeEntryRevealer.ts
2402 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-2402
removed time to display passcode screen
> [2402] removed time to display passcode screen

- src/api/explorer-service.ts
- src/components/templates/SearchAddress/index.tsx
- src/models/dtos/Explorer.ts
3162 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3162
Update Explorer API version to v2
> [3162] Update Explorer API version to v2

- src/api/explorer-service.ts
- src/components/base/Text/index.tsx
- src/components/templates/ExplorerAccount/index.tsx
- src/constants/colors.ts
- src/hooks/query/useTokensAndTransactions.ts
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
- src/screens/Asset/index.tsx
- src/screens/CreateWallet/screens/CreateWalletStep0/Step0.styles.tsx
- src/screens/CreateWallet/screens/CreateWalletStep0/index.tsx
- src/screens/CreateWallet/screens/CreateWalletStep1/index.tsx
- src/screens/CreateWallet/screens/CreateWalletStep2/Step2.styles.tsx
- src/screens/CreateWallet/screens/CreateWalletStep2/index.tsx
- src/screens/CreateWallet/screens/CreateWalletSuccess/CreateWalletSuccess.styles.tsx
- src/screens/CreateWallet/screens/CreateWalletSuccess/index.tsx
- src/screens/Settings/Settings.tsx
- src/screens/SetupPasscode/SetupPasscode.tsx
- src/screens/SetupPasscode/screens/ConfirmPasscode.tsx
- src/screens/SingleCollection/index.tsx
- src/screens/SingleCollection/styles.ts
- src/screens/Wallets/components/Header.tsx
2908 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-2908
styles bugfix
3167 https://inc4net.atlassian.net/browse/AMB-3167
change general color file
change general Text color
3168 https://inc4net.atlassian.net/browse/AMB-3168
The titles in such sections have not changed.
> AMB-2908 Styles bugfix

- src/components/svg/icons/SendReceive.tsx
- src/screens/NoWallet/components/Step.tsx
2810 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&search=2810&selectedIssue=AMB-2810
no-wallet svg stylefix
> [2810] no-wallet svg stylefix

- src/models/Explorer.ts
- src/screens/Search/index.tsx
3205 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3205
bugfix-> add one address to a group
> [3205] bugfix-> add one address to a group

- src/components/modular/WalletCard/index.tsx
- src/components/modular/WalletCard/styles.ts
- src/constants/shadow.ts
- src/screens/Wallets/index.tsx
[import/styles] import/styles bugfix
> [import/styles] import/styles bugfix

- src/components/templates/AddressList/components/SwipeableWalletItem.tsx
- src/components/templates/AddressList/index.tsx
- src/screens/Portfolio/components/ListsOfAddressGroup/components/GroupItem/index.tsx
- src/screens/Portfolio/components/ListsOfAddressGroup/index.tsx
- src/screens/Portfolio/components/PortfolioScreenTabs/index.tsx
3233 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3233
Remove Extra indentation from the header
> [3233] Remove Extra indentation from the header

- src/localization/locales/English.json
- src/localization/locales/Turkish.json
3199 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3199
Capitalize header n the "Asset Info" page
> [3199] Capitalize header n the "Asset Info" page

- src/screens/AMBMarket/index.tsx
3200 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3200
point 1,2 
Visual bugs with the "Market overview"
> [3200] Visual bugs with the "Market overview"

- src/hooks/usePasscodeEntryRevealer.ts
3234  https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3234
the old logic is back
> [3234] hot bugfix with passcode screen

- src/hooks/query/useCurrencyRate.ts
3244 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3244
bugfix BOND exchange price
> [3244] bugfix BOND exchange price

- src/screens/Portfolio/components/PortfolioScreenTabs/components/Collections/index.tsx
- src/screens/Portfolio/components/PortfolioScreenTabs/components/Collections/styles.ts
- src/screens/Portfolio/components/PortfolioScreenTabs/components/Watchlists/index.tsx
- src/screens/Portfolio/components/PortfolioScreenTabs/components/Watchlists/styles.ts
3250 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3250
bugfix with the switch in the "Watchlist"
> 3250 bugfix with the switch in the "Watchlist"

- src/components/composite/PopUpInfo/PopUpInfo.types.ts
- src/components/composite/PopUpInfo/index.tsx
- src/components/composite/PopUpInfo/styles.ts
- src/screens/AMBMarket/components/DetailedInfo.tsx
3249  https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3249
bugFix with tooltips in the "Stats" section.
> [3249] bugFix with tooltips in the "Stats" section.

- src/components/templates/TokenPicker/index.tsx
- src/screens/SendFunds/SendFunds.tsx
3246 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3246
3247 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3247
bugfix on sendFuns when user switch usd/crypto and select different tokens
> [3246, 3247] bugfix on sendFuns

- src/api/explorer-service.ts
3308 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3308
fix explorer pagination
> [3308]- fix explorer pagination

- src/components/templates/WalletTransactionsAndAssets/WalletAssets/index.tsx
- src/hooks/query/useExplorerAccounts.ts
- src/screens/Search/index.tsx
- src/screens/Search/styles.ts
3407 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3407
added pull to refresh on the "Explore" page
> [3407] added pull to refresh on the "Explore" page

- src/components/templates/ExplorerAccount/index.tsx
3509 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3509
bugfix in changing the percentage of the amount in US dollars in the address details
> [3509] bugfix USD amount in the address details

- src/components/templates/TransactionDetails/index.tsx
- src/screens/SendFunds/screens/SendFundsStatus/index.tsx
- src/screens/Settings/Settings.constants.tsx
- src/screens/Settings/Settings.tsx
3511 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3511
-- hidden "share" button on transaction details
-- hidden 'share' button after successfully sent
-- hidden "help centre' on settings menu
-- aligned setting item
> [3511] hide share buttons & help centre

- package.json
- src/components/templates/AMBPriceHistory/index.tsx
- src/localization/locales/Turkish.json
- yarn.lock
3514 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3514
update react-native-graph lib 
-- bugfix app crash on market page
-- replace Turkish text short form
> [3514] update react-native-graph lib 

- src/components/svg/icons/TelegramSettingsIcon.tsx
- src/components/svg/icons/index.ts
- src/screens/Settings/Settings.constants.tsx
- src/screens/Settings/Settings.tsx
3522 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3522
Align all components of the "Settings" page
> [3522] Align all components of the "Settings" page

- src/components/templates/BarcodeScanner/index.tsx
- src/contexts/Passcode/index.tsx
- src/hooks/usePasscodeEntryRevealer.ts
- src/screens/Wallets/components/Header.tsx
Resolve issue when OS requesting permission appertain to AppState focus changing & requesting biometric data to back to the app
> [AMB-3519] fix: resolve auth view when app requesting permission & footer dismissing

- src/utils/string.ts
refactor string util, that remove unnecessary **0** symbol & replace` (ex.) 01  > 1 `
> [AMB-3523] fix: resolve issue with replacing number at SendFunds flow

- src/hooks/query/useExplorerInfo.ts
- src/screens/Search/components/WalletItem.tsx
- src/screens/Search/index.tsx
3529 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3529
bugfix Incorrect data on the "Explorer" page
--added refetch explorer info after refresh page
--added logic when we not received explorer info
> [3529] bugfix Incorrect data on the "Explorer" page

- src/components/templates/BarcodeScanner/index.tsx
- src/hooks/usePasscodeEntryRevealer.ts
Fix Android bug, when user first time opened Scanner, cuz it anyway handled Request Permission as AppState change
> [AMB-3519] fix: resolve android bug with AppState changing while request permissions

- src/components/svg/BottomTabIcons/Watchlist.tsx
resolve truncating of Watchlist icon at Bottom Tab Navigation & Watchlist screen
> [AMB-3527] ui: change common width of watchlist icon

- src/screens/SendFunds/screens/SendFundsStatus/index.tsx
3448 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3448
handled error when transaction not procesed by 15 sec
> [3448] handled error when transaction not procesed by 15 sec

- src/components/modular/SingleAsset/index.tsx
- src/components/modular/TokenLogo/index.tsx
- src/components/svg/icons/NFTIcon.tsx
- src/components/svg/icons/index.ts
- src/hooks/query/useAMBPriceHistorical.ts
3576 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=622b4092a1245000688c2807&selectedIssue=AMB-3576
added NFT wallet icon
> [3576] added nft wallet icon

- src/hooks/usePasscodeEntryRevealer.ts
3594 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3594
return old passcode logic
> [3594] return old passcode logic

- src/screens/SendFunds/SendFunds.tsx
- src/utils/string.ts
AMB-3523: https://inc4net.atlassian.net/browse/AMB-3523
Resolve issue when user type 0.0..., validator removes zeros wrong
> [AMB-3523] fix: resolve bug with zero symbols

- src/components/templates/BottomSheetAddWalletToList/index.tsx
3595 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3595
remove space on group search screen
> [3595] remove space on group search screen

- src/components/modular/TransactionItem/index.tsx
2253 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-2253
handled contarctCall trans
> [2253] handled contarctCall trans

- src/api/explorer-service.ts
- src/api/getAllTokens.ts
- src/components/composite/BottomSheet/index.tsx
- src/utils/token.ts
> Cycles fix

- src/components/composite/BottomSheet/index.tsx
- src/components/modular/Toast/Toast.types.ts
- src/components/modular/Toast/index.tsx
Rewrote Toast notifications component with updating refs flow & correct types
> [AMB-2579] fix: resolve notifications bugs

- src/components/modular/WalletCard/index.tsx
- src/components/svg/icons/LogoGradient.tsx
3204 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3204
bugFix  Wallet card
> [3204] bugFix  Wallet card

- src/localization/locales/English.json
- src/localization/locales/Turkish.json
> [AMB-3738] ui (typography): update typography content inside stake bottom sheet

- patches/@neverdull-agency+expo-unlimited-secure-store+1.0.10.patch
- src/lib/cache.ts
3804 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3804
-fix duplicated bug
-fix bug with create multisig
> [hotfix multisig group]

- src/screens/SingleCollection/modals/BottomSheetAddNewAddressToGroup/index.tsx
3915 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-3915
remove line
> [AMB-3915] styles bugfix

- src/components/templates/Bridge/BottomSheetBridgeTransactionHistory/BottomSheetBridgeTransactionHistory.tsx
- src/components/templates/Bridge/BottomSheetBridgeTransactionPendingHistory/BottomSheetBridgeTransactionPendingHistory.tsx
- src/components/templates/Bridge/BridgeHistory/BridgeHistory.Transactions.tsx
- src/components/templates/Bridge/BridgeTransaction/index.tsx
- src/contexts/Bridge/Bridge.Context.tsx
- src/hooks/bridge/useBridgeNetworksData.ts
- src/lib/bridgeSDK/bridgeFunctions/parseBridgeTransaction.ts
- src/lib/bridgeSDK/sdk/index.ts
- src/models/dtos/Bridge.ts
4039 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4039
bugfix amount on transaction info modal and list
> [AMB- 4039] bugfix token amount on transaction info

- src/components/templates/Bridge/BottomSheetBridgeItemSelector/index.tsx
- src/components/templates/BridgeSelectorItem/index.tsx
- src/components/templates/BridgeSelectorItem/styles.tsx
- src/hooks/bridge/services/parseBridgeData.ts
- src/hooks/bridge/useBridgeNetworksData.ts
- src/lib/bridgeSDK/bridgeFunctions/bridgeTokensPairFilter.ts
- src/lib/bridgeSDK/sdk/index.ts
4045 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4045
--changed way to bridge withdraw
--added symbol for token on token-selector
4036 https://inc4net.atlassian.net/browse/AMB-4036
--clear input after successful withdrawal
> [4045]  Change Token Functionality

- src/hooks/bridge/useBridgeNetworksData.ts
4048 https://inc4net.atlassian.net/browse/AMB-4048
when user use max btn we had case when we get from backend data and show inccorect error
> [AMB-4048] bugfix- functionality maxBTN

- src/localization/locales/English.json
AMB-4055 https://inc4net.atlassian.net/browse/AMB-4055
bridge transaction history, visual bugfix
> [4055] bridge transaction history, visual bugfix

- src/components/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
- src/components/templates/Bridge/BottomSheetBridgeItemSelector/index.tsx
- src/components/templates/Bridge/BottomSheetBridgeTransactionPendingHistory/BottomSheetBridgeTransactionPendingHistory.tsx
- src/components/templates/Bridge/BridgeForm/BridgeForm.tsx
- src/components/templates/Bridge/BridgeForm/components/FeeInfo/FeeInfo.tsx
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
4050 https://inc4net.atlassian.net/browse/AMB-4050
visual bugfix
> [AMB-4050] visual bugfix

- src/constants/bridgeData.ts
- src/constants/bridgeNetworkNativeCoins.ts
- src/hooks/bridge/useBridgeNetworksData.ts
4057 https://inc4net.atlassian.net/browse/AMB-4057
Bugfix Network fee symbol
> [AMB-4057] bugfix Network fee symbol

- src/components/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
AMB-4049 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4049
bugfix decimal count on preview
> [AMB-4049] bugfix decimal count on preview

- src/localization/locales/Turkish.json
4004 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4004
Change translations to Turkish in Bridge
> [AMB-4004] bridge, translations

- src/components/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
- src/components/templates/Bridge/BottomSheetBridgeTransactionPendingHistory/BottomSheetBridgeTransactionPendingHistory.tsx
- src/components/templates/Bridge/BridgeNetworksSelected/BridgeNetworksSelected.tsx
- src/components/templates/Bridge/BridgeNetworksSelected/styles.ts
- src/constants/config.ts
- src/hooks/bridge/useBridgeNetworksData.ts
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
4004 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4004
add translations
4050 (p.1,2) https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4050
4056 max btn after error
> Bridge bugfix

- src/hooks/bridge/useBridgeNetworksData.ts
4080 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4080
bugfix endless loader on bridge transaction
> [AMB-4080] bug fix transaction loader

- src/components/templates/Bridge/BridgeForm/BridgeForm.tsx
- src/hooks/bridge/useBridgeNetworksData.ts
- src/hooks/useBridgeTransactionStatus.ts
- src/models/dtos/Bridge.ts
- src/utils/keepWSlive.ts
4031 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4031
BugFix - The status of Stage 3 in processing window does not actual.
> [AMB-4031] bugfix transaction status (stage3)

- src/localization/locales/Turkish.json
> [add translation]

- src/components/templates/Bridge/BridgeNetworksSelected/BridgeNetworksSelected.tsx
- src/components/templates/Bridge/BridgeNetworksSelected/styles.ts
4090 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4090
visual bugfix on preview
> [AMB-4090] visual bugfix on preview

- app.json
- src/components/templates/AccountActions/index.tsx
- src/constants/config.ts
- src/hooks/bridge/useBridgeNetworksData.ts
- src/screens/Settings/Settings.tsx
4073 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4073
bugfix - use max bth when balance less then 1
> [AMB-4073] max btn with low balance

- src/components/templates/Bridge/BridgeForm/BridgeForm.tsx
- src/hooks/bridge/useBridgeNetworksData.ts
4091 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4091
clear input after network/token selection
> [AMB-4091] clear input after network/token selection

- src/lib/bridgeSDK/sdk/withdraws.ts
4092 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4092
bugfix - Transaction Failure from BNB Chain to AirDAO
> [AMB-4092] bugfix transaction failed

- app.json
- src/components/templates/Bridge/BridgeForm/BridgeForm.tsx
- src/constants/config.ts
- src/hooks/bridge/useBridgeNetworksData.ts
- src/localization/locales/English.json
4079 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4079
change input-error logic
> [AMB-4079] change input-error logic

- src/components/modular/SingleAsset/index.tsx
- src/components/modular/TokenLogo/index.tsx
- src/components/templates/TransactionDetails/index.tsx
- src/constants/allToken.ts
- src/constants/config.ts
AMB 4133 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4133
Change mechanism of work with token icon
> [AMB-4133] Change mechanism of work with token icon

- src/components/templates/Bridge/BridgeForm/BridgeForm.tsx
4144 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4144
Visual bug with the "Preview" button on Android
> [AMB-4144] Visual bug with the "Preview" button on Android

- src/components/templates/Bridge/BridgeForm/BridgeForm.tsx
4079 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4079
style BugFix on bridge preview button
> [AMB-4079] style BugFix on bridge preview button

- src/components/templates/Bridge/BridgeForm/BridgeForm.tsx
- src/constants/config.ts
- src/contexts/Bridge/constants/index.ts
- src/hooks/bridge/useBridgeNetworksData.ts
4079 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4079
bugfix button error
> [AMB-4079-bugfix]

- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/screens/SendFunds/SendFunds.tsx
4144 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4144
> [AMB-4144] bugfix btn padding when the keyboard is open

- src/components/modular/TokenLogo/index.tsx
- src/components/templates/WalletTransactionsAndAssets/WalletAssets/index.tsx
- src/models/Token.ts
- src/models/dtos/TokenDTO.ts
4133 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4133
bugfix token logo when stitching wallet
> [bugfix token logo when stitching wallet]

- src/features/kosmos/components/templates/bottom-sheet-filters/index.tsx
- src/features/kosmos/components/templates/bottom-sheet-filters/styles.ts
4363 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4363
> [AMB-4363]

- src/screens/Kosmos/screens/KosmosMarket/index.tsx
4390 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4390
> [AMB-4390]

- src/screens/Kosmos/screens/KosmosMarket/index.tsx
4443 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4443
handle preview button on market screen
> AMB - 4443

- src/features/kosmos/components/templates/exact-market-token-tabs/tabs/transactions/index.tsx
4387 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4387
bigfix items flashing - remove props 'estimatedItemSize'
> [AMB-4387] remove flashlist estimatedItemSize

- src/features/kosmos/components/modular/balance/index.tsx
- src/features/kosmos/components/templates/exact-market-token-tabs/tabs/transactions/index.tsx
- src/features/kosmos/context/markets/markets.context.ts
- src/screens/Kosmos/screens/KosmosMarket/index.tsx
4440 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4440
fix bug with display bond balance on the market
> AMB - 4440

- src/screens/Kosmos/screens/KosmosMarket/index.tsx
4441 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4441 
disabled separated update on Android
> [AMB-4441] bugfix update kosmos transactions

- src/screens/Kosmos/screens/KosmosMarket/index.tsx
4441 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4441
remove loaders when user user pullDown refresh option
> [AMB-4441] remove loaders when user user pullDown refresher

- src/features/kosmos/components/templates/exact-market-token-tabs/tabs/transactions/index.tsx
- src/features/kosmos/components/templates/exact-market-token-tabs/tabs/transactions/styles.ts
https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4387
remove kosmos-transactions loader
> [AMB-4387] remove kosmos-transactions loader

- src/features/kosmos/components/templates/exact-market-token-tabs/tabs/transactions/index.tsx
4489 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4489
replace FlashList to VirtualizedList
> [AMB-4489] replace FlashList to VirtualizedList

- src/features/kosmos/lib/contracts/claim.ts
remove hardcode chain id params
> [remove hardcode chain_id]

- src/constants/config.ts
- src/features/kosmos/components/composite/index.ts
- src/features/kosmos/components/modular/index.ts
- src/features/kosmos/components/templates/market-tabs/index.tsx
- src/features/swap/utils/wrap-native-address.ts
> [resolve-swap/kosmos-cycles]

- src/features/kosmos/components/composite/markets-list/index.tsx
- src/features/kosmos/components/modular/user-orders-list/index.tsx
- src/features/kosmos/lib/hooks/use-transactions.ts
4532 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4532
> [AMB-4532] update orders when selected new walet

- src/components/modular/SingleAsset/index.tsx
- src/components/modular/TransactionItem/index.tsx
- src/components/modular/WalletCard/index.tsx
- src/components/templates/AccountActions/index.tsx
- src/components/templates/AccountList/AccountListItem.tsx
- src/components/templates/ExplorerAccount/ExplorerAccount.TransactionItem.tsx
- src/components/templates/TransactionDetails/index.tsx
- src/components/templates/WalletTransactionsAndAssets/WalletAssets/index.tsx
- src/constants/allToken.ts
- src/constants/variables.ts
- src/models/Explorer.ts
- src/models/Token.ts
- src/models/Transaction.ts
- src/models/dtos/TokenDTO.ts
- src/screens/Asset/index.tsx
- src/screens/Wallets/index.tsx
- src/utils/number.ts
4435 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4435
fix token balances when it less then ^10-7
> [AMB-4435] bugfix - small token balances

- src/appTypes/enums/TransactionType.ts
- src/components/modular/SingleAsset/index.tsx
- src/components/modular/TokenLogo/index.tsx
- src/components/templates/TransactionDetails/index.tsx
- src/components/templates/WalletTransactionsAndAssets/WalletAssets/index.tsx
- src/constants/allToken.ts
- src/hooks/getTokenNameFromDatabase.ts
- src/models/Token.ts
- src/models/dtos/TokenDTO.ts
4414 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4414
update token logo functionality
-when we don't have token address in our list we render default token logo.
4541 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4541
remove tokens mapping
> [AMB-4414] update token logo getter

- src/components/templates/TransactionDetails/index.tsx
- src/components/templates/TransactionDetails/styles.ts
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
4414 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4414
Visual bugs with transaction details 
handle FAIL transaction status
> [AMB-4414] Visual bugs with transaction details

- src/screens/Kosmos/screens/KosmosMarket/index.tsx
4489 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4489
Transactions are shown after a certain time after the loader disappears.
> [AMB-4489] bugfix with loader on market

- src/screens/Kosmos/screens/KosmosMarket/index.tsx
- src/screens/Kosmos/screens/KosmosMarket/styles.ts
4482 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4482
remove loader on android under chart graph
> [AMB-4482] loader on android

- src/features/kosmos/components/modular/balance/index.tsx
- src/features/kosmos/components/modular/buy-bond-button/index.tsx
- src/features/kosmos/components/templates/bottom-sheet-preview-purchase/index.tsx
- src/features/kosmos/lib/hooks/use-balance.ts
4641 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4641
disabled preview window after kosmos transaction
> [AMB-4641] disabled preview window after kosmos transaction

- src/features/kosmos/components/modular/balance/index.tsx
- src/features/kosmos/components/templates/exact-market-token-tabs/index.tsx
- src/features/kosmos/components/templates/exact-market-token-tabs/tabs/buy-bond/index.tsx
- src/features/kosmos/lib/hooks/use-balance.ts
- src/screens/Kosmos/screens/KosmosMarket/index.tsx
4629 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4629
rewrite  get token balance logic
add loader when we wait new token balance
> [AMB-4629] rewrite token balance logic

- src/components/templates/WalletTransactionsAndAssets/WalletAssets/index.tsx
- src/contexts/SendCrypto/SendCrypto.types.ts
- src/hooks/query/useCurrencyRate.ts
- src/hooks/useUSDPrice.ts
- src/screens/SendFunds/SendFunds.tsx
4435 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4435
> [AMB-4435] hotfix

- src/features/swap/components/modular/input-with-token-select/styles.ts
pull request includes updated styles to avoid twitching value inside swap form input on android platform
> [AMB-4583] ui(styles): update swap form input styles

- src/models/Token.ts
4781 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4781
bugfix app crash
> [AMB-4781] bugfix app crash

- src/screens/CreateWallet/screens/CreateWalletStep2/Step2.styles.tsx
4811 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4811
> [AMB-4811] recovery phrase window

- src/screens/CreateWallet/screens/CreateWalletStep2/Step2.styles.tsx
4811 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4811
> [4811] recovery phrase window

- src/screens/CreateWallet/screens/CreateWalletStep0/Step0.styles.tsx
- src/screens/Settings/Settings.tsx
- src/screens/Settings/screens/About/index.tsx
- src/screens/Settings/screens/About/styles.ts
- src/screens/Settings/styles.ts
--create wallet (step0) checkbox fix
--settings version replace to "About"
> Setting hot-fix

- src/appTypes/navigation/wallets.ts
- src/components/svg/icons/Back.tsx
- src/components/templates/WalletTransactionsAndAssets/index.tsx
- src/features/send-funds/components/templates/header/styles.ts
- src/features/wallet-assets/components/templates/header/index.tsx
- src/features/wallet-assets/lib/hooks/use-barcode.ts
- src/navigation/stacks/Tabs/HomeStack.tsx
navigation from search address by qrCode, to address item screen
> [bugfix-navigation-error-from-scanQRCode]

- src/appTypes/navigation/settings.ts
- src/screens/CreateWallet/screens/CreateWalletStep0/index.tsx
- src/screens/CreateWallet/screens/CreateWalletStep1/index.tsx
- src/screens/SetupPasscode/SetupPasscode.tsx
- src/screens/SetupPasscode/screens/ConfirmPasscode.tsx
4980 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4980
change buttons name on create wallet screen & setup passcode screen
> [ui: change-buttons-name]

- src/screens/CreateWallet/screens/CreateWalletStep2/MnemonicSelected.tsx
- src/screens/CreateWallet/screens/CreateWalletStep2/Step2.styles.tsx
[AMB-4985] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4985
> ui:-padings-on-mnemonic-box

- src/appTypes/navigation/root.ts
- src/appTypes/navigation/settings.ts
- src/appTypes/navigation/tabs.ts
- src/navigation/stacks/Tabs/SettingsStack.tsx
- src/screens/NoWallet/index.tsx
- src/screens/SetupPasscode/SetupPasscode.styles.tsx
- src/screens/SetupPasscode/SetupPasscode.tsx
- src/screens/SetupPasscode/screens/ConfirmPasscode.tsx
[AMB-4984] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4984
bugfix: navigation from welcome screen -> passcode screen 
ui: change header font size on setup passcode & approve passcode
> bugfix: passcode navigation

- src/screens/StakingPool/components/Stake/Stake.tsx
- src/screens/StakingPool/components/Withdraw/Withdraw.tsx
hotfix: 
-- add types
-- check props typeof
> hotfix: kosmos-redesign withdraw/stake

- src/features/wallet-connect/components/composite/wallet-approval-view/index.tsx
- src/localization/locales/Turkish.json
- src/screens/StakingPool/components/Stake/Stake.tsx
[AMB-5024] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5024
- disabled stake button when pools isActive === false
- enabled withdraw button when pools isActive === false
- enabled all functionality when isActive === true
- add new translation
- dependency hotfix
> AMB - 5024

- src/features/wallet-connect/components/composite/wallet-approval-view/index.tsx
- src/screens/SendFunds/index.tsx
[AMB-5028] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5028
-- button title show amount error
> ui: send section button title

- src/components/templates/InputWithTokenSelect/components/BottomSheetTokensList/index.tsx
- src/features/send-funds/components/composite/tokens-list/index.tsx
- src/screens/SendFunds/components/confirm-tx/index.tsx
[AMB-5015] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=712020%3Af18645c7-dbbd-4dac-9474-f7fd52e75e44&selectedIssue=AMB-5015
remove margin on token list modal/ send funds section
> ui: bugfix on token list modal

- src/components/modular/BalanceRow/index.tsx
[AMB-5039} https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5039
style bugfix on <InputWithTokenSelect/>
> ui: style bugfix on token max balance

- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
[AMB-5044] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5044
-- change error text in button on bridge section
> ui: bridge error text in button

- src/features/bridge/templates/BottomSheetBridgePreview/components/GeneralPreviewTemplate/GeneralPreviewTemplate.tsx
- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/bridge/templates/BridgeNetworksSelected/BridgeNetworksSelected.tsx
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
[AMB-5049] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5049
add bridge transaction success screen
> ui: add bridge transaction success screen

- src/screens/SetupPasscode/SetupPasscode.tsx
- src/screens/SetupPasscode/screens/ConfirmPasscode.tsx
[AMB-4980] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4980
change set passcode screen/confirm passcode screen, confirm button background
> ui: change passcode confirm button background

- src/screens/SendFunds/index.tsx
[AMB-5028] 
point 2 
https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5028
change button name on send funs
> ui: change button name on send funs

- src/features/bridge/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
[AMB-5047] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5047
rename bridge preview button
> ui: remane bridge preview button

- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/bridge/templates/BridgeForm/styles.ts
[AMB-5045] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5045
make input disabled frame smaller
> ui: make disabled frame smaller

- src/features/bridge/templates/BottomSheetBridgeTransactionPendingHistory/components/BridgeTransactionPendingTemplate/BridgeTransactionPendingTemplate.tsx
- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/bridge/templates/BridgeTransaction/components/Status/Status.styles.tsx
- src/features/bridge/templates/BridgeTransaction/components/Status/Status.tsx
[AMB-5048] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5048
-add destination network name on bridge preview
- align transaction status text on bridge preview screen
> ui: bugfix on bridge preview

- src/screens/SetupPasscode/SetupPasscode.styles.tsx
- src/screens/SetupPasscode/SetupPasscode.tsx
- src/screens/SetupPasscode/screens/ConfirmPasscode.tsx
[AMB-4984] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4984
--block navigation.goBack from SetupPasscode screen
--remove SafeAreaView from SetupPasscode screen& ConfirmPasscode screen
--create the same styles on SetupPasscode & ConfirmPasscode
> fix: block navigation from setup passcode

- src/screens/Notifications/index.tsx
[AMB- 5011] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5011
point 1
--change notification settings screen title, when user goes from notification page
> ui: change notification settings screen title

- src/screens/CreateWallet/screens/CreateWalletStep2/Step2.styles.tsx
- src/screens/Notifications/components/notification-box/index.tsx
[AMB-4985] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4985
--add horizontal padding on mnemonic container
> ui:  horizontal padding on mnemonic container

- src/appTypes/notification.ts
- src/models/Notification.ts
- src/screens/Notifications/components/notification-box/index.tsx
[AMB-5057] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5057
--change notification title
> fix: bugfix notification title

- src/models/Notification.ts
- src/screens/SetupPasscode/screens/ConfirmPasscode.tsx
[AMB-4984] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b
add bottom border on ConfirmPassword screen header
> bugfix: abb bottom botred on confirm passwork header

- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/bridge/templates/BridgeForm/styles.ts
[AMB-5045] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5045
-- change logic to get width & height input disabled component
> bugfix: disable input container style

- src/screens/Bridge/Bridge.tsx
[AMB-5070] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5070
-- clear input when user go back from bridge
> bugfix: clear input when user go back from bridge

- src/features/bridge/templates/BridgeForm/styles.ts
- src/screens/Bridge/Bridge.tsx
-- clear input when user go to bridge screen
-- remove red background from input disabled component
> hotfx: clear input after go back from bridge

- src/features/bridge/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
[AMB-5047] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5047
show preview header while we getting bridge transaction
> ui: show preview header while we getting bridge transaction

- src/screens/Settings/screens/About/About.MenuItem.tsx
- src/screens/Settings/screens/AppPreferences/components/PrefrencesMenuItem.tsx
- src/screens/Settings/screens/AppPreferences/components/modals/BottomSheetSelectLanguage/index.tsx
- src/screens/Settings/screens/NotificationSettings/index.tsx
[AMB-5077] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5077
setting pages styles
> fix: settings item style

- src/features/bridge/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
[AMB-5070] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5045
clear input when transaction in procces
> fix: clear input when transaction in procces

- src/screens/ImportWalletMethods/screens/ImportWallet/ImportWallet.tsx
[AMB-5073] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5073
scroll down when user enter recovery phrase
> ui: scroll down when user enter recovery phrase

- src/features/kosmos/components/modular/buy-bond-button/index.tsx
[AMB-5080] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5080
clear kosmos input after successfully  transaction
> fix: clear kosmos input after transaction

- src/features/bridge/templates/BridgeForm/styles.ts
[AMB - 5045] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5045
bridge section - change input disabled template style
> ui: change input disabled template style

- src/components/composite/TextOrSpinner/index.tsx
- src/features/swap/components/modular/review-swap-button/index.tsx
- src/features/swap/components/modular/submit-swap-actions/index.tsx
- src/features/swap/components/templates/bottom-sheet-preview-swap/components/error/index.tsx
- src/features/swap/components/templates/bottom-sheet-preview-swap/index.tsx
- src/features/swap/lib/hooks/use-swap-bottom-sheet-handler.ts
- If your not supposed to render loadingLabel, only spinner, you have to pass `loadingLabel={undefined}` as prop value
- Swap bottom sheet method updates
- Bottom sheet actions updated
> fix(swap): update render bottom sheet method & text-or-spinner component render loadingLabel optional

- src/features/lists/lib/hooks/use-list-actions.ts
- src/screens/SingleCollection/modals/BottomSheetAddNewAddressToGroup/index.tsx
- src/utils/deviceSpecification.ts
AMB-5136 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5136
--change firebase event logic when user delete/add address to group
--add iPhone13 device height to isSmallScreen variable
> bugfix: address add to group firebase event

- src/screens/StakingPool/components/Stake/Stake.tsx
AMB-5138 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5138
remove second stake_error event
> bugfix: remove second stake_error event

- src/screens/StakingPool/components/Withdraw/Withdraw.tsx
AMB-5143 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5143
add stake/unstake event only to api methods
> bugfix: add stake/unstake event only to api methods

- src/api/staking/staking-service.ts
- src/components/templates/AccountActions/components/Bridge.tsx
- src/components/templates/AccountActions/components/Kosmos.tsx
- src/components/templates/AccountActions/components/Send.tsx
- src/components/templates/AccountActions/components/Staking.tsx
- src/components/templates/AccountActions/components/Swap.tsx
- src/components/templates/AddWalletToList/index.tsx
- src/components/templates/BottomSheetCreateRenameGroup/index.tsx
- src/components/templates/SearchAddress/index.tsx
- src/features/bridge/context/Bridge.Context.tsx
- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/bridge/utils/getBridgeFee.ts
- src/features/kosmos/components/composite/claimable-order-card-details/index.tsx
- src/features/kosmos/components/composite/markets-list/index.tsx
- src/features/kosmos/components/modular/buy-bond-button/index.tsx
- src/features/lists/lib/hooks/use-list-actions.ts
- src/features/swap/components/modular/submit-swap-actions/index.tsx
- src/features/swap/lib/hooks/use-swap-actions.ts
- src/features/wallet-assets/components/modular/assets-account-actions-list/index.tsx
- src/features/wallet-assets/components/templates/header/index.tsx
- src/hooks/cache/useWatchlist.ts
- src/lib/firebaseEventAnalytics/index.ts
- src/navigation/components/TabBar/index.tsx
- src/screens/SendFunds/index.tsx
- src/screens/Settings/screens/Explore/index.tsx
- src/screens/SingleCollection/modals/BottomSheetAddNewAddressToGroup/index.tsx
- src/screens/StakingPool/components/Stake/Stake.tsx
- src/screens/StakingPool/components/Withdraw/Withdraw.tsx
- src/utils/wallet.ts
5145 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5145
--add all bridge event
-- remove bridge error alerts
> bugfix: add all bridge event

- src/components/svg/icons/v2/harbor/StakeIcon.tsx
- src/components/svg/icons/v2/harbor/index.ts
- src/components/templates/DropDownPanel/index.tsx
- src/features/harbor/components/base/preview-modules/form-template/index.tsx
- src/features/harbor/components/base/preview-modules/success-template/copy-hash/index.tsx
- src/features/harbor/components/base/preview-modules/success-template/copy-hash/styles.tsx
- src/features/harbor/components/base/stake-info-container/index.tsx
- src/features/harbor/components/base/tiers-info-container/index.tsx
- src/features/harbor/components/tabs/stake-amb-tab/index.tsx
- src/features/harbor/components/tabs/stake-amb-tab/styles.ts
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
- src/screens/Harbor/ProcessStake/ProcessStake.tsx
- src/utils/deviceSpecification.ts
5163 https://inc4net.atlassian.net/browse/AMB-5163
--harbor-stake screen ui bugfix
--change isSmallScreenLogic
--add autoscroll to tiers info system
> ui: bugfix, change isSmalScreen logic, add scroll to tiers info

- src/api/harbor/harbor-service.ts
- src/constants/config.ts
- src/features/harbor/components/base/preview-modules/form-template/index.tsx
- src/features/harbor/components/base/preview-modules/success-template/index.tsx
- src/screens/Harbor/WithdrawRequests/WithdrawRequests.style.tsx
- src/screens/Harbor/WithdrawRequests/WithdrawRequests.tsx
- src/screens/Harbor/WithdrawRequests/components/index.ts
- src/screens/Harbor/WithdrawRequests/components/request-item/index.tsx
- src/screens/Harbor/WithdrawRequests/components/request-item/styles.ts
5165 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5165
bugfix: harbor transaction date info, 
refactor: withdraw request screen
> ui: bugfix harbor transaction date info, withdraw request refactor

- app.config.js
- src/features/products/components/base/product-list-item/index.tsx
- src/features/products/entities/_products.tsx
- src/features/products/utils/product.ts
- src/lib/firebaseEventAnalytics/constants/CustomAppEvents.ts
- src/lib/firebaseEventAnalytics/sendFirebaseEvent.ts
5144 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5144
add firebase event to  product redirect
> event: add firebase event from product

- src/constants/config.ts
- src/features/harbor/components/harbor-preview/index.tsx
- src/features/harbor/components/harbor-preview/model.ts
- src/features/harbor/components/tabs/withdraw-stake-reward-tab/index.tsx
- src/screens/Harbor/ProcessStake/ProcessStake.tsx
5166 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5166
clear input after successfully withdraw/stake
> fix: clear input after successfully withdraw/stake

- src/features/harbor/components/harbor-preview/index.tsx
AMB-5167 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5167
hide modal then change modal content
> fix:  hide modal then change modal content

- src/features/harbor/components/base/preview-modules/success-template/index.tsx
- src/features/harbor/components/base/tiers-selector/index.tsx
- src/features/harbor/components/tabs/withdraw-reward-only-tab/index.tsx
- src/features/harbor/components/tabs/withdraw-reward-only-tab/styles.ts
- src/features/harbor/components/tabs/withdraw-stake-reward-tab/index.tsx
- src/features/harbor/components/tabs/withdraw-stake-reward-tab/styles.ts
- src/features/harbor/hooks/parseDataHelpers/parseWithdrawReward.ts
- src/features/harbor/hooks/parseDataHelpers/parseWithdrawStakePreview.ts
- src/screens/Harbor/ProcessStake/ProcessStake.tsx
- src/screens/Harbor/ProcessStake/styles.tsx
AMB-5168 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5168
ui bugfix on harbor withdraw
> ui: ui bugfix on harbor withdraw

- src/entities/harbor/constants/index.ts
- src/features/harbor/components/base/preview-modules/success-template/index.tsx
- src/features/harbor/components/harbor-preview/index.tsx
- src/features/harbor/components/harbor-preview/model.ts
- src/features/harbor/hooks/parseDataHelpers/models.ts
- src/features/harbor/hooks/processHelpers/resultHandler.ts
AMB-5172 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5172
remove date block from success preview
> fix: transaction hash display always

- src/features/harbor/components/base/tiers-selector/index.tsx
5177 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5177
add header on tier info tooltip
> ui: add header on tier info tooltip

- src/screens/Harbor/StakeHarborScreen/StakeHarborScreen.tsx
5182 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5182
update harbor user-info when user change wallet
> fix: update harbor user info when user change wallet

- src/features/harbor/components/base/stake-info-container/index.tsx
- src/features/harbor/components/base/tiers-selector/index.tsx
- src/features/harbor/components/harbor-preview/index.tsx
- src/features/products/components/templates/products-list/styles.ts
- src/screens/Harbor/ProcessStake/ProcessStake.tsx
- src/screens/Harbor/StakeHarborScreen/StakeHarborScreen.tsx
harbor bugfix
[AMB-5182] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&search=5182&selectedIssue=AMB-5182
update all user data when active wallet changed
[AMB-5177] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&search=5177&selectedIssue=AMB-5177
add header on tier tooltip content
[AMB-5169] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&search=5169&selectedIssue=AMB-5169
update wallet balance on harbor screen
> Harbor bugfix

- src/api/harbor/harbor-service.ts
- src/lib/firebaseEventAnalytics/constants/CustomAppEvents.ts
- src/lib/firebaseEventAnalytics/sendFirebaseEvent.ts
- src/localization/locales/Turkish.json
AMB-5175 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5175
add harbor firebase event
> event: add harbor firebase event

- src/features/harbor/components/base/tiers-selector/index.tsx
AMB-5179 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5179
bugfix tooltip on tier selector
> ui: bugfix tooltip on tier selector

- src/components/modular/TokenLogo/index.tsx
> fix: import methods

- src/localization/locales/English.json
- src/localization/locales/Turkish.json
5191 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5191
change translations
> ui: chande translations

- src/features/harbor/components/tabs/withdraw-reward-only-tab/styles.ts
- src/features/harbor/components/tabs/withdraw-stake-reward-tab/styles.ts
- src/screens/Harbor/ProcessStake/ProcessStake.tsx
- src/screens/Harbor/ProcessStake/styles.tsx
- src/screens/Harbor/WithdrawHarborScreen/WithdrawHarborScreen.tsx
5174 https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5174
fix: autoscroll when input onFocus
> fix: autoscroll when input onFocus

- src/screens/SetupPasscode/screens/SuccessSetupSecurity.tsx
[AMB-5194] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5194
bugfix  error appears of accessible on the device
> fix: biometric auth error

- src/screens/Settings/screens/Watchlist/components/BottomSheetConfirmRemoveGroup/index.tsx
- src/screens/Settings/screens/Watchlist/components/ListsOfAddressGroup/components/GroupItem/index.tsx
[AMB-5195 ] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5195
bugfix animation lags when closing remove group modal
> bugfix: close modal  animation fix

- src/screens/Harbor/ProcessStake/components/StakedBalanceInfo/styles.tsx
- src/screens/Harbor/ProcessStake/styles.tsx
- src/screens/Harbor/WithdrawHarborScreen/styles.tsx
[AMB-5191] 
--2 change harbor-amb-stake background color
--3 change harbor-amb-withdraw background color
> ui change background color

- src/components/templates/InputWithoutTokenSelect/index.tsx
- src/components/templates/InputWithoutTokenSelect/styles.tsx
[AMB-5192] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5192
on harbor-amb-stake screen make inputs arrow smaller
> ui: make arrow smaller

- src/models/dtos/WatcherInfo.ts
- src/screens/Settings/screens/About/DebugInfo/components/DebugInfoItem/index.tsx
- src/screens/Settings/screens/About/DebugInfo/components/DebugInfoItem/styles.tsx
- src/screens/Settings/screens/About/DebugInfo/index.tsx
- src/screens/Settings/screens/About/DebugInfo/styles.tsx
- src/screens/Settings/screens/About/index.tsx
[AMB-4674] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-4674
add debug module with info:
-- current/firebase/backend push token 
-- user ID
-- device ID
-- watchlist  addresses
> debug: add debug module

- src/features/passcode/lib/hooks/use-passcode-actions.ts
[AMB- 5194] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5194
turn off all biometric erros
> fix: remove all biometric errors

- src/components/templates/BottomSheetRemoveAddressFromCollection/index.tsx
[AMB-5195] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5195
bugfix animation when user delete address from group
> ui: bugfix animation when user delete address from group

- src/components/templates/BottomSheetRemoveAddressFromCollection/index.tsx
- src/lib/firebaseEventAnalytics/sendFirebaseEvent.ts
- src/screens/Settings/screens/Watchlist/components/BottomSheetConfirmRemoveGroup/index.tsx
- src/screens/Settings/screens/Watchlist/components/ListsOfAddressGroup/components/GroupItem/index.tsx
[AMB-5195] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5195
set delay for close modal window - 500 ms
remode firebase event alert
> Firebase event/ update close modal logic

- src/screens/Settings/screens/About/DebugInfo/components/DebugInfoItem/index.tsx
- src/screens/Settings/screens/About/DebugInfo/index.tsx
add user watcher link to debug section on settings
> ui: add watcher link to debug section

- src/screens/Harbor/WithdrawRequests/WithdrawRequests.style.tsx
- src/screens/Harbor/WithdrawRequests/WithdrawRequests.tsx
- src/screens/Settings/screens/About/DebugInfo/index.tsx
[AMB-4674] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b
--bugfix watcher link on debug section
--make gray background on  withdraw lick
> bugfix: debug link, withdraw list height

- src/appTypes/blockchain/CryptoCurrencyCode.ts
- src/components/svg/icons/KosmosToken.tsx
- src/screens/Settings/screens/About/components/DebugMode/components/DebugItem/index.tsx
- src/screens/Settings/screens/About/components/DebugMode/index.tsx
- Added 'KOS' to the CryptoCurrencyCode enum.
- Moved the import of IconProps in KosmosToken icon component for better organization.
- Reordered imports in DebugItem component for consistency.
> feat: add KOS currency code and improve KosmosToken icon import

- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/harbor/components/tabs/withdraw-reward-only-tab/index.tsx
- src/features/harbor/components/tabs/withdraw-stake-reward-tab/index.tsx
[AMB-5214] https://inc4net.atlassian.net/browse/AMB-5214
--while user dont enter amount > 0 text in button is 'Enter amount', add it on Harbor, Bridge section
> bugfix: Dont allow a zero transaction

- src/screens/ImportWalletMethods/screens/ImportWallet/styles.ts
[AMB-5212] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5212
> ui: add padding on import wallet button

- src/features/swap/lib/contracts/swap.ts
- src/features/swap/lib/hooks/use-swap-actions.ts
- src/features/swap/lib/hooks/use-swap-interface.ts
- Introduced a new `swapArgsCallback` function to streamline argument preparation for token swaps.
- Updated `swapExactTokensForTokens` to utilize the new callback for better clarity and maintainability.
- Modified `useSwapActions` to include `tokenToReceive` for accurate swap execution.
- Ensured `priceImpact` is set to zero if undefined in the swap interface for better user experience.
- Improved overall logic for handling token amounts and slippage tolerance in the swap process.
> feat: enhance swap functionality and improve token handling

- src/screens/NoWallet/index.tsx
[AMB-5245] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5245
Make a looping animation for the welcome screen
> ui: Make a looping animation for the welcome screen

- Providers.tsx
- src/features/swap/components/composite/preview-information/index.tsx
- src/features/swap/components/templates/bottom-sheet-preview-swap/components/error/index.tsx
- src/features/swap/components/templates/bottom-sheet-preview-swap/components/success/index.tsx
- src/features/swap/context/initials.ts
- src/features/swap/context/swap.context.tsx
- src/features/swap/entities/tokens.ts
- Updated the `SwapContext` to initialize selected tokens with a new structure, including USDC support.
- Refactored `PreviewInformation` to enhance multi-hop route detection logic.
- Modified `ErrorSwapView` and `SuccessSwapView` to delay navigation status updates for better user experience.
- Cleaned up unused imports and constants in `initials.ts` to streamline the codebase.
> dex: improve swap context and UI components

- src/features/products/entities/_products.tsx
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
[AMB-5250] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5250
change harbor description on product list
> ui: translation

- src/features/swap/components/composite/balance/index.tsx
- src/features/swap/components/modular/index.ts
- src/features/swap/components/modular/swap-currency-rate/index.tsx
- src/features/swap/components/templates/swap-form/index.tsx
- src/features/swap/lib/hooks/use-swap-better-rate.ts
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
- Simplified the `Balance` component by removing unused context variables and improving error handling logic.
- Introduced a new `SwapCurrencyRate` component to display real-time swap rates and toggle token order.
- Updated the `SwapForm` to integrate the new `SwapCurrencyRate` component.
- Modified the `useSwapBetterRate` hook to support better rate fetching and token order toggling.
- Updated localization strings for clarity in user messaging.
> dex-components: enhance swap functionality and UI components

- src/screens/SetupPasscode/SetupPasscode.styles.tsx
- src/screens/SetupPasscode/SetupPasscode.tsx
- src/screens/SetupPasscode/screens/ConfirmPasscode.tsx
[AMB-5235] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5235
BugFix - Visual bugs on IOS.
> ui: fix dome ios visual bugs

- src/localization/locales/Turkish.json
- Changed "Gönderiyorsun" to "Gönderdiğiniz" for improved clarity in user messaging.
- Removed an unnecessary empty line in the localization file.
> fix(localization): update Turkish translation for swap functionality

- src/features/swap/lib/contracts/swap.ts
- Removed redundant calls to getAmountsOut and getAmountsIn.
- Directly calculated amountOutMin and amountOutMax using parsed input amounts.
- Improved code clarity and efficiency in the swap functionality.
> refactor(swap): simplify amount calculations in swapArgsCallback

- src/screens/KosmosOrderList/index.tsx
- src/screens/KosmosOrderList/styles.ts
[AMB-5248] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5248
bugfix: ui bugfix on kosmos screen
> bugfix: ui bugfix on kosmos screen

- src/components/svg/icons/TokenXENA.tsx
- src/features/swap/components/base/bottom-sheet-review-token-item/index.tsx
- src/features/swap/components/modular/review-swap-button/index.tsx
- Replaced the existing TokenXENA icon implementation with a new SVG structure, enhancing visual fidelity and scalability.
- Updated the BottomSheetReviewTokenItem component to use SwapStringUtils for amount transformation instead of NumberUtils, improving consistency in amount formatting.
- Enabled the disabled state for the ReviewSwapButton component, ensuring proper button behavior based on the disabled prop.
> refactor(icons, swap): update TokenXENA icon and improve swap components

- src/screens/Wallets/index.tsx
- Integrated useTokensAndTransactions hook to fetch tokens and transactions for the selected account.
- Replaced ethers.js balance check with a balanceReducer for improved balance validation.
- Simplified the logic for determining if the selected account balance is zero.
- Updated imports to include _tokensOrNftMapper for better token and NFT management.
> wallets: enhance token handling and locking actions

- src/features/swap/components/modular/swap-currency-rate/index.tsx
- src/features/swap/components/templates/swap-form/index.tsx
- src/features/swap/utils/multi-route.ts
- src/features/swap/utils/token-plate.ts
- src/screens/Swap/index.tsx
- Added a check to determine if the path includes the SAMB address.
- Updated the filtering logic to exclude the AMB address from available tokens if SAMB is included in the path, improving route generation accuracy.
> refactor(swap): enhance route generation logic to exclude AMB when SAMB is present in the path

- src/features/swap/lib/contracts/swap.ts
- src/features/swap/lib/hooks/use-swap-actions.ts
- src/screens/BarcodeScanner/index.tsx
- Refactored swapMultiHopExactTokensForTokens to consistently use wrapNativeAddress for path handling.
- Updated the mock address in BarcodeScanner to a more complex format for testing purposes.
> refactor(swap): update path handling in swap functions and improve mock address in BarcodeScanner

- src/features/bridge/templates/BottomSheetBridgeNetworkSelector/index.tsx
- src/features/bridge/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
- Changed swiperIconVisible from true to false in both BottomSheetBridgeNetworkSelector and BottomSheetBridgePreview components for improved UI consistency.
> refactor(bottom-sheet): update swiperIconVisible prop to false

- src/components/templates/WalletNoNFTsView/index.tsx
- Added translation support using react-i18next to the WalletNoNFTsView component.
- Replaced static text with localized strings for the empty NFT state header and subheader, enhancing the user experience for different languages.
> feat(wallet-no-nfts-view): integrate i18n for localization

- src/components/modular/AutoScrollBox/index.tsx
- src/components/modular/AutoScrollBox/styles.tsx
- src/components/modular/index.ts
- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/bridge/templates/BridgeForm/styles.ts
- src/features/harbor/components/tabs/harbor-withdraw-tabs/index.tsx
- src/features/harbor/components/tabs/withdraw-reward-only-tab/index.tsx
- src/features/harbor/components/tabs/withdraw-stake-reward-tab/index.tsx
- src/features/harbor/components/tabs/withdraw-stake-reward-tab/styles.ts
- src/screens/Harbor/ProcessStake/ProcessStake.tsx
- src/screens/Harbor/ProcessStake/styles.ts
- src/screens/Harbor/WithdrawHarborScreen/WithdrawHarborScreen.tsx
[AMB-5265] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5265
--add auto scroll component to app
--change button workflow
> ui: change button logic

- src/localization/locales/English.json
- src/localization/locales/Turkish.json
- src/screens/BarcodeScanner/index.tsx
[AMB-5264] https://inc4net.atlassian.net/browse/AMB-5264
translation: add Turkish phrase on Scan QR Code screen
> translation: add Turkish phrase

- src/screens/Harbor/ProcessStake/ProcessStake.tsx
remove bold styles from button on harbor amb stake screen
> bugfix: button text

- src/features/swap/components/modular/submit-swap-actions/index.tsx
- src/features/swap/lib/contracts/swap.ts
- src/features/swap/lib/hooks/use-swap-actions.ts
- src/features/swap/lib/hooks/use-swap-interface.ts
- Enhanced swap functions (`swapExactETHForTokens`, `swapMultiHopExactTokensForTokens`, `swapExactTokensForTokens`, `swapExactTokensForETH`) to include an `estimateGas` parameter for gas estimation.
- Updated `useSwapActions` hook to support gas estimation during token swaps.
- Improved code readability and maintainability by consolidating argument handling logic for gas estimation.
> feat(swap): add estimateGas option to swap functions

- src/features/wallet-assets/components/templates/header/index.tsx
- src/features/wallet-connect/components/base/wallet-session-item/index.tsx
- src/features/wallet-connect/components/composite/wallet-sessions-label/index.tsx
- src/features/wallet-connect/components/composite/wallet-sessions-list/index.tsx
- src/features/wallet-connect/lib/hooks/index.ts
- src/features/wallet-connect/lib/hooks/use-connections-controller.ts
- Updated components to utilize useConnectionsController for session management, enhancing clarity and consistency.
- Modified HomeHeader, WalletSessionsLabel, WalletSessionsList, and WalletSessionItem to reflect the new hook usage.
- Improved error handling in WalletSessionItem by ensuring the active session bottom sheet is dismissed on error.
> refactor(wallet-connect): replace useWalletConnectContextSelector with useConnectionsController

- src/features/wallet-connect/components/base/wallet-session-item/index.tsx
- Removed conditional check for filtered pairings before dismissing the active session bottom sheet, ensuring it is always dismissed when the function is called.
- Simplified the logic for setting active sessions, enhancing code clarity and maintainability.
> refactor(wallet-session-item): streamline session dismissal logic

- src/features/swap/lib/contracts/swap.ts
- src/features/swap/lib/hooks/use-swap-interface.ts
- src/features/swap/utils/provider-fee.ts
- src/features/wallet-connect/components/composite/wallet-approval-view/index.tsx
- src/features/wallet-connect/lib/hooks/use-initialize-wallet-kit.ts
- src/features/wallet-connect/utils/helpers.ts
- src/screens/BarcodeScanner/index.tsx
- Introduced `wrapEstimatedGas` utility to handle gas estimation with error handling in swap functions, enhancing robustness.
- Updated swap functions to utilize `wrapEstimatedGas`, ensuring consistent error management during gas estimation.
- Added `validateAndFilterSessions` function to filter valid wallet connect sessions, improving session management and error handling.
- Refactored wallet connect components to use the new session validation logic, ensuring only active sessions are displayed.
- Updated mock address in BarcodeScanner for better alignment with wallet connect standards.
> refactor(swap, wallet-connect): improve gas estimation and session validation

- src/features/wallet-connect/components/composite/wallet-approval-view/index.tsx
- Added `walletConnectStep` to the context selector for improved state management.
- Updated the approval process to dismiss the bottom sheet on connection error, enhancing user experience.
- Refactored dependencies in the useEffect hook to include `walletConnectStep`, ensuring proper reactivity.
> refactor(wallet-connect): enhance WalletConnectApprovalView logic

- src/features/wallet-connect/components/composite/wallet-approval-view/index.tsx
- Removed the `validateAndFilterSessions` function call and directly set active sessions using `walletKit.getActiveSessions()`, streamlining session handling and improving code clarity.
> refactor(wallet-connect): simplify session management in approval view 

- src/screens/Settings/Settings.tsx
- Replaced the import of SafeAreaView from 'react-native' with 'react-native-safe-area-context' to ensure proper handling of safe area insets, improving layout consistency across devices.
> refactor(settings): update imports for SafeAreaView component

- src/features/harbor/components/tabs/withdraw-stake-reward-tab/index.tsx
[AMB-5341] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5341
bugfix: change max button setter logic
> bugfix: change max button setter logic

- jest/setup.js
- Added Jest mocks for @walletconnect/react-native-compat
- Added Jest mocks for @reown/walletkit WalletKit and IWalletKit
- Added Jest mock for @walletconnect/core Core
> test(setup): add mocks for WalletConnect and WalletKit dependencies

- src/components/svg/icons/v2/index.ts
- src/components/svg/icons/v2/product/ProductBridge.tsx
- src/components/svg/icons/v2/product/ProductHarbor.tsx
- src/components/svg/icons/v2/product/ProductKosmos.tsx
- src/components/svg/icons/v2/product/ProductStake.tsx
- src/components/svg/icons/v2/product/ProductSwap.tsx
- src/components/svg/icons/v2/product/index.ts
- src/constants/colors.ts
- src/constants/config.ts
- src/features/products/entities/_products.tsx
[AMB-5344] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5344
ui: center product icons
> ui: center product icons

- app.config.js
- src/components/modular/StakingPool/index.tsx
--new build settings
--remove unused styles
> build: new settings

- src/localization/locales/English.json
add whitespace to english translation file
> hotfix: add whitespace to translation file

- src/api/browser-service.ts
- src/appTypes/navigation/common.ts
- src/appTypes/navigation/wallets.ts
- src/constants/colors.ts
- src/constants/config.ts
- src/entities/browser/model/browser-store.ts
- src/entities/browser/model/index.ts
- src/entities/browser/model/types.ts
- src/features/browser/components/templates/disclaimer-modal/index.tsx
- src/features/browser/components/templates/disclaimer-modal/styles.ts
- src/features/browser/components/templates/index.ts
- src/features/products/components/base/product-list-item/index.tsx
- src/features/products/components/templates/products-list/index.tsx
- src/features/products/components/templates/products-list/styles.ts
- src/features/products/entities/_products.tsx
- src/features/products/utils/index.ts
- src/features/products/utils/parseWebProduct.tsx
- src/features/products/utils/product.ts
- src/features/wallet-connect/components/composite/wallet-approval-view/styles.ts
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
- src/navigation/stacks/AppInit.tsx
- src/navigation/stacks/Tabs/HomeStack.tsx
- src/navigation/stacks/Tabs/ProductsStack.tsx
- src/screens/Browser/index.tsx
- src/screens/Products/index.tsx
- src/utils/hasDigits.ts
- src/utils/index.ts
-- connect config file to app
-- add disclaimer modal when user open no airDao app
> feat: connect products config file to app

- src/lib/crypto/TransferDispatcher.ts
-- change wait time for transaction response to 17 seconds
> transactions: change wait time for transaction response to 17 seconds.

- src/features/browser/components/modular/browser-header/index.tsx
- src/features/products/entities/_products.tsx
- src/features/products/utils/product.ts
- src/screens/Browser/index.tsx
- src/screens/Browser/styles.tsx
-- add goBack function to right swipe
-- add goForward function to left swipe
> feat: add swipe action to goBack/goForward

- src/features/bridge/templates/BottomSheetBridgePreview/BottomSheetBridgePreview.tsx
- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
[AMB-5355] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5355
fix: adjust rounding precision for bridge transactions
> fix: adjust rounding precision for bridge transactions

- jest/setup.js
- src/constants/variables.ts
- src/features/swap/lib/hooks/use-swap-better-currency.ts
- src/features/swap/lib/hooks/use-swap-better-rate.ts
- src/features/swap/utils/index.ts
- src/features/swap/utils/is-trade-better.ts
Introduce isTradeBetter utility to compare trade routes with a minimum threshold improvement
- Create new utility function to evaluate trade route efficiency
- Refactor swap route selection to use the new comparison method
- Improve multi-hop and single-hop route selection logic
- Add consistent trade comparison across exact-in and exact-out trade scenarios
> feat(swap): add trade comparison utility for multi-hop route selection

- src/features/harbor/components/base/preview-modules/form-template/index.tsx
- src/features/harbor/components/templates/harbor-preview/index.tsx
Update error handling in transaction review and improve button loading state management:
- Simplify error checking logic in transaction processing
- Adjust button disabled state to include loading condition
- Update button styling for loading and disabled states
> fix(harbor): refine transaction error handling and button loading states

- src/lib/crypto/TransferDispatcher.ts
[AMB-5379] https://inc4net.atlassian.net/browse/AMB-5379
--added a delay function to introduce a wait period between transaction status checks.
--introduced a MAX_RETRIES constant (set to 5) to control the number of attempts when fetching a transaction receipt.
-- Replaced the hardcoded retry limit (3) with MAX_RETRIES to improve maintainability and allow easy adjustments.
> transaction: add retries to get transaction receipt

- src/screens/Settings/screens/Explore/index.tsx
- Use InteractionManager for search address focus and scanner interactions
- Improve performance of search-related UI interactions
- Refactor header and search address component rendering
> fix(ui/explore): optimize search address interactions with InteractionManager

- src/components/modular/BalanceRow/index.tsx
- src/features/swap/components/composite/balance/index.tsx
- src/features/swap/components/modular/input-with-token-select/index.tsx
- src/features/swap/components/modular/swap-currency-rate/index.tsx
- src/features/swap/lib/hooks/use-swap-better-currency.ts
- src/features/swap/lib/hooks/use-swap-better-rate.ts
- src/features/swap/lib/hooks/use-swap-price-impact.ts
- src/features/swap/lib/hooks/use-swap-select-tokens.ts
- Integrate price impact calculation for single and multi-hop routes
- Enhance route selection logic to prioritize routes with lower price impact
- Add support for custom path price impact calculation
- Refactor multi-hop impact getter to handle dynamic path scenarios
> feat(swap): improve multi-hop route selection with price impact optimization

- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
[AMB - 5473] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5473
--Increasing the value of the constant GAS_FEE_BUFFER for the correct calculation of USD tokens.
> fix: Increasing the value of the constant GAS_FEE_BUFFER

- src/components/modular/BalanceRow/index.tsx
- src/components/templates/InputWithTokenSelect/index.tsx
- src/features/bridge/templates/BridgeForm/BridgeForm.tsx
- src/features/bridge/templates/BridgeForm/components/TokenSelectData/TokenSelectData.tsx
[AMB-5472] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5472
show correct token balance and amount on all networks
> fix: show correct token balance on bridge

- src/features/swap/components/composite/balance/index.tsx
- Add isFetchingBalance check to balance validation
- Update dependency array in useMemo hook to include isFetchingBalance
> fix: improve balance validation logic in swap component

- src/features/swap/components/modular/swap-currency-rate/index.tsx
- src/features/swap/lib/hooks/use-swap-better-rate.ts
- src/features/swap/utils/transformers.ts
- Update rate calculation logic in swap hooks
- Add new transformCurrencyRate utility method
- Refactor rate computation to handle different input scenarios
- Improve precision and formatting of currency rate display
> fix(swap): improve currency rate transformation and calculation

- src/features/swap/lib/hooks/use-swap-better-currency.ts
- src/features/swap/lib/hooks/use-swap-fields-handler.ts
- Improve multi-hop path selection criteria
- Add more flexible price impact comparison
- Introduce optional UI hop array update parameter
- Adjust default price impact thresholds
- Refactor trade calculation methods
> fix(swap): enhance multi-hop swap route selection logic

- src/features/swap/components/modular/input-with-token-select/index.tsx
- src/features/swap/components/modular/review-swap-button/index.tsx
- src/features/swap/components/modular/swap-currency-rate/index.tsx
- src/features/swap/context/swap.context.tsx
- src/features/swap/lib/hooks/use-all-liquidity-pools.ts
- src/features/swap/lib/hooks/use-swap-better-currency.ts
- src/features/swap/lib/hooks/use-swap-better-rate.ts
- src/features/swap/lib/hooks/use-swap-fields-handler.ts
- src/features/swap/lib/hooks/use-swap-price-impact.ts
- src/features/swap/utils/transformers.ts
- Add constant PRICE_IMPACT_THRESHOLD for more flexible multi-hop route selection
- Replace hardcoded 0.3 threshold with configurable constant
- Improve multi-hop swap route selection logic with dynamic threshold
> feat(swap): add loading state for liquidity pools 

- src/screens/StakingPool/components/Withdraw/BottomSheet/Withdraw.Preview.tsx
- Add null check for amount in insufficient funds calculation
- Refactor balance extraction from useAMBEntity hook
- Prevent potential errors when calculating withdrawal balance
> fix(staking): improve withdraw preview balance validation

- src/api/staking/staking-service.ts
- src/screens/StakingPool/components/Withdraw/BottomSheet/Withdraw.Preview.tsx
- Update unstake method to use overrides.value for gas estimation
- Remove redundant gas fee calculation in staking service
- Add null check for estimated gas in withdraw preview component
> fix(staking): optimize unstake gas estimation and preview rendering

- src/features/swap/components/composite/balance/index.tsx
- src/features/swap/components/modular/input-with-token-select/index.tsx
- src/utils/number.ts
- Update input value transformation to handle exact in/out trade scenarios
- Enhance max token amount button disabled state with pools loading check
- Refactor number utility to better handle decimal and comma formatting
> fix(swap): improve token input and max amount selection logic

- src/features/swap/lib/contracts/swap.ts
- Remove 'SupportingFeeOnTransferTokens' method variants
- Streamline swap method selection logic for different token swap scenarios
- Reduce complexity in method name and argument selection
> fix(swap): simplify swap method selection for native and token swaps

- src/constants/config.ts
- src/entities/browser/model/browser-store.ts
- src/entities/browser/model/types.ts
- src/features/browser/components/modular/browser-header/index.tsx
- src/features/browser/components/modular/browser-header/styles.ts
- src/features/browser/components/templates/bottom-sheet-approve-browser-action/index.tsx
- src/features/browser/lib/injectable.provider.ts
- src/features/browser/lib/rpc-middleware.ts
- src/features/browser/types/rpc-methods.types.ts
- src/features/products/entities/_products.tsx
- src/screens/Browser/index.tsx
- src/screens/Browser/styles.tsx
-- remove wallet selector icon
-- add post message with product title data
-- add title to browser action from web product 
-- change ui features
> feat: hide and rewrite some ui logic

- src/constants/config.ts
- src/features/browser/constants/index.ts
- src/features/browser/constants/rpc.ts
- src/features/browser/lib/injectable.provider.ts
- src/features/browser/lib/middleware-helpers/handleWalletConnection.ts
- src/features/browser/lib/middleware-helpers/walletRevokePermissions.ts
- src/features/browser/lib/permissions-handler.ts
- src/features/browser/lib/rpc-methods.ts
- src/features/browser/lib/rpc-middleware.ts
- src/features/browser/utils/connect-wallet.ts
- src/localization/locales/Turkish.json
-create config for testnet
-create config for stage
> feat: new dev-stage-prod config for browser

- src/features/harbor/components/modular/withdrawal-button/index.tsx
- src/features/harbor/components/templates/bottom-sheet-withdraw-transaction-with-action/index.tsx
- src/features/harbor/lib/hooks/use-withdrawal-actions.ts
- src/screens/Harbor/WithdrawHarborPoolScreen/WithdrawHarborPoolScreen.tsx
- Add estimated gas and AMB balance checks for withdrawal button
- Update withdrawal actions to handle gas estimation scenarios
- Enhance bottom sheet withdraw transaction with additional balance context
> fix(harbor): improve withdrawal button and transaction handling

- src/features/swap/components/composite/balance/index.tsx
- src/features/swap/components/modular/input-with-token-select/index.tsx
- src/features/swap/components/modular/submit-swap-actions/index.tsx
- src/utils/__tests__/numbers.test.ts
- src/utils/number.ts
- Add isPoolsLoading check to balance rendering and validation
- Refactor input value transformation for exact in/out trades
- Update number utility to handle significant digits more precisely
- Enhance submit swap actions button rendering logic
> fix(swap): improve balance and input handling with pools loading state

- src/features/swap/components/composite/balance/index.tsx
- src/features/swap/lib/contracts/swap.ts
- src/features/swap/lib/hooks/use-swap-actions.ts
- src/features/swap/lib/hooks/use-swap-better-currency.ts
- src/features/swap/lib/hooks/use-swap-price-impact.ts
- src/features/swap/utils/price-impact.ts
- Add support for fee-on-transfer tokens in swap methods
- Enhance native token balance calculation with gas estimation
- Update swap actions to handle trade direction more accurately
- Modify price impact calculation to use full percentage
- Refactor balance selection with added timeout for smoother UX
> fix(swap): improve native token swap handling and gas estimation

- src/constants/config.ts
- src/entities/browser/model/types.ts
- src/features/products/components/templates/products-list/index.tsx
- src/features/products/utils/parseWebProduct.tsx
-- Added platform dependency to determine product visibility
--  Implemented filtering logic on the mobile app side
--  Supports multiple platforms (e.g., ios, android)
--  Scalable structure for future platform extensions
> feat: add platform-based filtering for web products

- src/constants/config.ts
- src/features/browser/components/modular/browser-header/index.tsx
- src/features/browser/lib/middleware-helpers/ethSignTypesData.ts
- src/features/browser/lib/rpc-methods.ts
- src/features/browser/lib/rpc-middleware.ts
- src/features/browser/types/rpc-methods.types.ts
- src/features/products/utils/productSequence.ts
- src/screens/Browser/index.tsx
-- add snapshot product
-- improve WebView navigation handling
-- add go back button on android
-- add dynamic GoBackButton visibility
> feat: add new product on product screen

- src/entities/harbor/components/composite/bottom-sheet-review-transaction/index.tsx
- src/features/harbor/components/templates/bottom-sheet-review-transaction-with-action/index.tsx
- src/features/harbor/lib/hooks/use-approve-contract.ts
- src/screens/Harbor/StakeHBRScreen/StakeHBRScreen.tsx
- Added `isApprovalRequired` and `approving` props to manage approval state.
- Updated transaction label based on approval status.
- Conditional rendering for transaction details based on approval requirements.
- Integrated approval logic in StakeHBRScreen for gas estimation.
- Adjusted timeout for setting approval state in useApproveContract hook.
> feat(stake-hbr): enhance transaction approval flow in BottomSheetReviewTransaction component

- src/components/modular/PermissionItem/index.tsx
- src/components/modular/PermissionItem/styles.tsx
- src/components/svg/icons/v2/browser/DefaultPerrmissionsIcon.tsx
- src/components/svg/icons/v2/browser/index.ts
add default icon if product don't has or don't send icon link
> feat: add default permission icon

- src/screens/Settings/Settings.tsx
- src/screens/Settings/styles.ts
[AMB-5632] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5632
--add scroll in Manage permission screen
> ui: add scroll in settings screen

- src/components/modular/PermissionItem/index.tsx
[AMB-5634] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5634
fix: remove async function from permission manager
> fix: remove async function from permission manager

- src/features/browser/components/templates/browser-modal/index.tsx
- src/features/browser/components/templates/browser-modal/styles.ts
- src/localization/locales/English.json
- src/localization/locales/Turkish.json
[AMB-5642] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5642
Visual bugs with "Security warning" poup.
> ui: browser modal bugfix

- src/components/templates/AllProductPermissions/index.tsx
- src/features/browser/lib/middleware-helpers/handleWalletConnection.ts
- src/features/browser/lib/middleware-helpers/walletRevokePermissions.ts
- src/features/browser/lib/permissions.manager.ts
- src/hooks/useSettingsWalletActions.ts
- src/screens/Browser/index.tsx
[AMB-5633] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5633
--bugfix "Manage permissions"  screen displays the website connection without wallet.
> bugfix: displays the website connection without wallet

- src/features/wallet-connect/components/composite/wallet-connect-tx-approval/index.tsx
- src/features/wallet-connect/lib/hooks/use-decode-callback.ts
- Removed loading state from `WalletConnectTxApproval` to streamline rendering.
- Enhanced token symbol handling to default to `CryptoCurrencyCode.AMB` when necessary.
- Updated `useDecodeCallbackData` to correctly retrieve amount from `rawArgs`.
> refactor: improve token handling in WalletConnectTxApproval and update amount retrieval in useDecodeCallbackData

- src/screens/Browser/index.tsx
- Added useMemo to optimize background state handling for Android devices.
- Updated WebView rendering logic to conditionally display based on app state, improving performance during inactive states.
- Cleaned up imports by adding useAppState hook for better state management.
> fix(android/webview): prevent rendering WebView component while app is not active

- package.json
- src/components/composite/BottomSheet/BottomSheet.types.ts
- src/constants/config.ts
- src/features/browser/components/templates/bottom-sheet-approve-browser-action/index.tsx
- src/features/browser/lib/middleware-helpers/ethDecrypt.ts
- src/features/browser/lib/middleware-helpers/ethEncryptionPublicKey.ts
- src/features/browser/lib/middleware-helpers/ethGasPrice.ts
- src/features/browser/lib/middleware-helpers/ethGenericProviderHandler.ts
- src/features/browser/lib/middleware-helpers/index.ts
- src/features/browser/lib/rpc-middleware.ts
- src/features/browser/types/rpc-methods.types.ts
-- added handling of new browser methods
> feat: added handling of browser methods

- src/entities/browser/lib/hooks/index.ts
- src/entities/browser/lib/hooks/use-audio-handler.ts
- src/screens/Browser/index.tsx
- Added useAudioHandler to manage audio playback within the BrowserScreen.
- Removed conditional rendering of the WebView based on app state, ensuring it is always displayed.
- Cleaned up unused imports for better code clarity.
> feat(browser): integrate audio handler

- app.config.js
- src/constants/config.ts
- Bumped app version from 1.4 to 1.5 in app.config.js.
- Bumped Android versionCode from 179 to 181.
- Changed default configuration from testnet to production in config.ts.
> build: update app version and configuration settings

- src/features/send-funds/components/base/tokens-list-item/index.tsx
- Integrated wallet context to determine if the token is a native token.
- Updated token logo retrieval logic to account for native tokens, improving visual representation.
- Refactored memoization for better performance and clarity.
> feat(tokens-list-item): enhance token identification logic in TokensListItem component

- package.json
- src/components/base/TokenImageIpfsWithShimmer/index.tsx
- src/components/modular/TokenLogo/index.tsx
- yarn.lock
- Added react-native-fast-image dependency to improve image loading performance in the TokenImageIpfsWithShimmer component.
- Refactored TokenImageIpfsWithShimmer to utilize FastImage for better caching and loading experience.
- Updated the TokenLogo component to include a ShimmerLoader while the image is loading, enhancing the user interface.
> feat: add react-native-fast-image for optimized image loading

- src/localization/locales/Turkish.json
> feat: add translation

- src/screens/SendFunds/index.tsx
[5769] https://inc4net.atlassian.net/jira/software/c/projects/AMB/boards/6?assignee=60ae0bbd1ee723006c080e4b&selectedIssue=AMB-5769
set default token to list if user does not have one
> feat: set default token to list if user does not have one

- src/constants/config.ts
- src/features/swap/lib/abi/PAIR.ts
- src/features/swap/lib/hooks/index.ts
- src/features/swap/lib/hooks/use-all-liquidity-pools.ts
- src/features/swap/lib/hooks/use-swap-all-balances.ts
- src/features/swap/lib/hooks/use-trade-price-listener.ts
- src/features/swap/utils/wrap-native-address.ts
- src/screens/Swap/index.tsx
- Changed default configuration from production to testnet in config.ts.
- Added new 'Swap' event to PAIR.ts for better tracking of swap transactions.
- Introduced useTradePriceListener hook in index.ts for improved trade price tracking.
- Refactored useAllLiquidityPools to return all pairs instead of results for consistency.
- Updated useSwapAllBalances to utilize Config for token filtering, ensuring better management of common tokens.
> feat: add "Swap" event listener to handle pool reserves updates

- app.config.js
- Added compileSdkVersion, targetSdkVersion, and buildToolsVersion to the Android configuration in app.config.js for improved compatibility and performance.
> build(android-api): update Android SDK configuration

- app.config.js
- Updated versionCode from 185 to 186 in app.config.js to reflect the latest build version.
> build(android-api): increment versionCode for Android configuration
